image: docker:18.09

services:
  - docker:18.09-dind

stages:
  - publish
  - build_publish_non_major

publish:
  only:
    - master
  stage: publish
  before_script:
    - apk add --update make git openssh openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - git submodule init
    - git submodule update --remote --recursive
    - echo "$DOCKER_PASSWORD" | docker login docker.codeheroes.io -u "$DOCKER_USERNAME" --password-stdin
    - git config --global user.email "gitlab@codeheroes.io"
    - git config --global user.name "GitlabCI"
  script:
    - export CURRENT_VERSION=`sed -n 's/.*version = \([0-9\.]*\)/\1/p' Makefile`
    - export VERSION_STRIPPED=${CURRENT_VERSION#*.}
    - export VERSION="0.$((VERSION_STRIPPED+1))"
    - chmod +x update-version.sh
    - ./update-version.sh
    - make publish

    - git status
    - git checkout HEAD Makefile
    - chmod +x update-version.sh
    - ./update-version.sh
    - export URL_HOST=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
    - git remote set-url origin "https://gitlab-ci-token:${CI_ACCESS_TOKEN}@${URL_HOST}"
    - git add Makefile
    - git commit -m "CI build version ${VERSION} [skip ci]"
    - git push origin HEAD:master
    - docker logout docker.codeheroes.io

publish_non_major:
  except:
    - master
  only:
    variables:
      - $PUBLISH_NON_MAJOR == "true"
  stage: build_publish_non_major
  before_script:
    - apk add --update openssh openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - git submodule init
    - git submodule update --remote --recursive
    - chmod +x update-version.sh
    - echo "$DOCKER_PASSWORD" | docker login docker.codeheroes.io -u "$DOCKER_USERNAME" --password-stdin
  script:
    - export CURRENT_VERSION=`sed -n 's/.*version = "\([0-9\.]*\)"/\1/p' Makefile
    - export VERSION_STRIPPED=${CURRENT_VERSION#*.}
    - export VERSION="0.$((VERSION_STRIPPED)).$((CI_JOB_ID))"
    - ./update-version.sh
    - make publish
    - docker logout docker.codeheroes.io
